services:
  - type: web
    name: portfolio
    env: static
    buildCommand: |
      rm -rf node_modules
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: ./out
    node:
      version: 18.x